# Deep Learning with Tensorflow

In [3]:
import tensorflow as tf
import numpy as np


## Creating Tensors
* Tensors are the basic building blocks in writing AI programs in tensorflow. A tensor can basically be defined as a multi-dimensional array of values.
* Common tensors include the type variable, constant and zeros. Example intialization below:

In [9]:
variable_tensor = tf.Variable(["a", "b", "c"])
constant_tensor = tf.constant(["v", "d", "m"])

print(variable_tensor)
print(constant_tensor)

#The zero, ones and fills functions create tensors of a single value. 
# The required arguement is only the shape of the desired tensor.

<tf.Variable 'Variable:0' shape=(3,) dtype=string, numpy=array([b'a', b'b', b'c'], dtype=object)>
tf.Tensor([b'v' b'd' b'm'], shape=(3,), dtype=string)


## Checking the rank of a Tensors

In [12]:
rank_tensor = tf.Variable([["hey", "ki", "de"], ["ko", "th", "fg"], ["d", "e", "b"]])
print(rank_tensor)
tf.rank(rank_tensor) #rank 2 (vector)

<tf.Variable 'Variable:0' shape=(3, 3) dtype=string, numpy=
array([[b'hey', b'ki', b'de'],
       [b'ko', b'th', b'fg'],
       [b'd', b'e', b'b']], dtype=object)>


<tf.Tensor: shape=(), dtype=int32, numpy=2>

## Transforming Tensors
* The dominant transformation we will make use of is the reshape function.

In [13]:
vec = tf.reshape(rank_tensor, [9,1])
print(vec)

tf.Tensor(
[[b'hey']
 [b'ki']
 [b'de']
 [b'ko']
 [b'th']
 [b'fg']
 [b'd']
 [b'e']
 [b'b']], shape=(9, 1), dtype=string)


## Basic mathematical operations on tensors
* These include add, multiply, subtract, divide. These functions are accessed through the tf package.

In [ ]:
tf.add() #Takes in an argument of the tensors to be operated on
tf.multiply()
tf.divide()
tf.subtract()

# Exponents and logarithms
* Deep learning algorithms often make use of exponential and logarithmic math. 